version: '3.9'

services:
  urlshortenerapi:
    image: urlshortenerapi
    container_name: urlshortenerapi
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5227
    ports:
      - 5227:5227
      - 52027:52027

  urlredirectservice:
    image: urlredirectservice
    container_name: urlredirectservice
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5228
    ports:
      - 5228:5228
      - 52028:52028

  loginservice:
    image: loginservice
    container_name: loginservice
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5229
    ports:
      - 5229:5229
      - 52029:52029
