version: '3.9'

services:
  urlshortenerapi:
    image: urlshortenerapi
    container_name: urlshortenerapi
    restart: always
    ports:
      - 3000:80
      - 3001:123

  urlredirectservice:
    image: urlredirectservice
    container_name: urlredirectservice
    restart: always
    ports:
      - 3002:80

  loginservice:
    image: loginservice
    container_name: loginservice
    restart: always
    ports:
      - 3003:80
