version: '3.9'

services:
  shorturldb:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: shorturldb
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ECUtbildning2022!
    volumes:
      - ./volumes/shortURL:/var/opt/mssql/data

  urlshortenerapi:
    image: urlshortenerapi
    container_name: urlshortenerapi
    restart: always
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: 'secret'
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:52027;http://+:5227
      ASPNETCORE_HTTPS_PORT: 52027
    volumes:
      - ./volumes/certificates/.aspnet/https:/https/
    ports:
      - 5227:5227
      - 52027:52027
    depends_on:
      - shorturldb

  urlredirectservice:
    image: urlredirectservice
    container_name: urlredirectservice
    restart: always
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: 'secret'
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:52028;http://+:5228
      ASPNETCORE_HTTPS_PORT: 52028
    volumes:
      - ./volumes/certificates/.aspnet/https:/https/
    ports:
      - 5228:5228
      - 52028:52028
