# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  urlshortenerapi:
    image: urlshortenerapi
    build:
      context: .
      dockerfile: UrlShortenerAPI/Dockerfile
    ports:
      - 5227:5227
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
